### ISSUE TITLE
Preset against lovesickness and broken heart

### ISSUE THREAD

**Issue by SecUpwN** [GiorgioRegni/Binaural-Beats#19]
Good morning @GiorgioRegni, first of all: Huge thanks for this neat app (although it looks like your repo is currently not very well maintained) and especially for publishing it on my belloved F-Droid store!

Here's my request: My girlfriend left me two days ago. It fuckin' hurts. I would love to have a preset designed to stabilize my inner feelings, glue my heart and get away from all the very deep pain. I am a strong man, I will get over it, but if your app could do a good job to assist people like me, that would rock. Before anyone tells me to use the already existing preset `Morphine pain killer`: It's not working here.

* **Update:** Seems like my girlfriend is coming back. I still would like this preset for others to appear.

**Comment by GiorgioRegni** [comment]
Glad to know your girlfriend is coming back :)
It sounds like you want the preset to do a lot of things at the same time, I am thinking that the preset Unity is what you're looking for here.

**Comment by SecUpwN** [comment]
>It sounds like you want the preset to do a lot of things at the same time, I am thinking that the preset Unity is what you're looking for here.

Thanks, my girlfriend is back since several days, she realized that her decision without talking about and clearing up the underlying problems was stupid. I'll try your recommended preset in a quiet minute.
