### ISSUE TITLE
Are you still maintaining this project? 

### ISSUE THREAD

**Issue by kevencarneiro** [GiorgioRegni/Binaural-Beats#22]
Hi, I'm a developer who wants to contribute in this project and I have a UX Designer friend that also wants to contribute. But before we start, we need to know if you are still maintaining this project and accepting help.

**Comment by GiorgioRegni** [comment]
Absolutely, thanks for in advance for your help!

**Comment by GiorgioRegni** [comment]
@kevencarneiro have you looked at this branch: https://github.com/GiorgioRegni/Binaural-Beats/tree/dev/materialdesign this is the latest

**Comment by kevencarneiro** [comment]
OK, I'll check out. Thanks!

**Comment by GiorgioRegni** [comment]
Hey, what do you think @kevencarneiro ?

**Comment by kevencarneiro** [comment]
Sorry for the long time. I've installed the new version and I liked the concept of the cards, but now I'm in a project and can't help from now until September. If you want my help in something that isn't code I can help you right now but I can start to code only in September.

**Comment by GiorgioRegni** [comment]
Hi @kevencarneiro, do you have more time to help now?
