### ISSUE TITLE
Dark theme

### ISSUE THREAD

**Issue by tgc12** [GiorgioRegni/Binaural-Beats#23]
I love the new design, but I'll love more if there was an option to use a dark theme.

**Comment by GiorgioRegni** [comment]
Thanks for the feedback @tgc12, I think it's relatively easy to add a button to switch theme

**Comment by adeshp96** [comment]
I would like to work on this. But is this code base up to date? The Android App was last updated on August 17, 2017 whereas this was last updated on Jan 26, 2016.
