### ISSUE TITLE
F-Droid version is not current.

### ISSUE THREAD

**Issue by Locash** [GiorgioRegni/Binaural-Beats#24]
One of the best apps for BB therapy. Truly Awesome app.
Just informing that the fdroid version is 1.2  last update was '12 well behind the playstore version.

**Comment by GiorgioRegni** [comment]
Actually I never uploaded to F-droid, I assumed they were pulling it automatically or maybe somebody else published there? Because I don't have access to that listing... @Locash any idea?

**Comment by Locash** [comment]
Correct fdroid pulls,builds and signs it.(to insure security)
Here is the fdroid wiki on Binaural beats. It has the details why the updating stopped.(the biggest I see is the issue( Play library) part of google repository, proprietary library being used.  
https://f-droid.org/wiki/page/com.ihunda.android.binauralbeat

The developer FAQ has a lot of useful info.
https://f-droid.org/wiki/page/FAQ_-_App_Developers
