### ISSUE TITLE
I would like to help with localisation

### ISSUE THREAD

**Issue by jjgh** [GiorgioRegni/Binaural-Beats#25]
I can help translating to Italian (with a very high accuracy). 
Thing is, people, especially the elders, sometimes have difficulties sleeping and I would like to introduce them to binaural waves listening.

Your app is the cleanest on the Play store, but it lacks translation and you can't expect 50+ yo to know English well enough to understand how to use your app, at least where I live.

So, want me to help? I'd be happy to do so!
And your app could reach way more people and possibly help them feel better!

**Comment by GiorgioRegni** [comment]
all the strings are in https://github.com/GiorgioRegni/Binaural-Beats/blob/dev/materialdesign/app/src/main/res/values/strings.xml

I can help you get setup,

**Comment by jjgh** [comment]
@GiorgioRegni great, I'll look into that ASAP. 
Should I follow the usual procedure of forking, editing, then making a pull request?

**Comment by GiorgioRegni** [comment]
Yes, perfect, you can fork then please start from the dev/materialdesign branch and do a PR,
thanks!

**Comment by GiorgioRegni** [comment]
Hi @jjgh, how are you doing on the translation? I went to do an update to the market soon so it'd be great to include your stuff.
