### ISSUE TITLE
Reported screen shutting down mid program issues

### ISSUE THREAD

**Issue by GiorgioRegni** [GiorgioRegni/Binaural-Beats#33]

**Comment by GiorgioRegni** [comment]
Fixed in #32

**Comment by JawnZ** [comment]
I'm still having this issue on version 8.0

**Comment by JawnZ** [comment]
ah, maybe I misunderstood your fix.

I know in the past I have been able to use this app with the screen off, but it looks like now you are forcing the screen to stay on to fix the issue.

That's not a great fix, is it possible to go back to before when it would work as a background audio app?
