### ISSUE TITLE
add more background sounds

### ISSUE THREAD

**Issue by thegreenman** [GiorgioRegni/Binaural-Beats#6]
I think we need a few more looping background sounds such as rainstorm, babbling brook, or beach waves. I know too many will just cause bloat, but one or two more would be nice. 

I have some royalty free ones here if you want them... let me know.  They can probably be compressed without too much loss of fidelity.

**Comment by SecUpwN** [comment]
>Inside the email I sent you was brook.zip/ three files waves.ogg brook.ogg rain.ogg

Interesting to see that this Issue is still open since 4 years. You should re-send that E-Mail. ;-)

**Comment by GiorgioRegni** [comment]
yeah... 4 years ...
let me dig for that email
